{% set version = '5.6.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lpsolve
  version: {{ version|replace("-", "_") }}

source:
  fn: lpSolve_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lpSolve_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lpSolve/lpSolve_{{ version }}.tar.gz
  sha256: d5d41c53212dead4fd8e6425a9d3c5767cdc5feb19d768a4704116d791cf498d

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('lpSolve')"           # [not win]
    - "\"%R%\" -e \"library('lpSolve')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lpSolve
  license: LGPL-2
  summary: Lp_solve is freely available (under LGPL 2) software for solving linear, integer and
    mixed integer programs. In this implementation we supply a "wrapper" function in
    C and some R functions that solve general linear/integer problems, assignment problems,
    and transportation problems. This version calls lp_solve version 5.5.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
