travis:
  secure:
    BINSTAR_TOKEN: w4ZIZlc5e79eP35hzecTGeZdaaAi0z3gA8n+ZkJIcfgZpy+5ERV7qBXKhFYlO4b8e4EleLz392tfu6EunGpNj4/nbcVNQMYUe8vYUtaOn+6QJWftjystGXPcLPVTonx7pCMZhqmqeks9pbbPiz+vrtTJpNj8AhFOARrseXSWIKB5DaeZnGD3EHK7iBCIbTBEGUVKu1t9gGnWR7wj6zrcooKRtC2P4Ij37mPaS1LFEmwDiB0fr7Uv+I6uxgB3ULbbm+BTkn8Wx2ZrUTVd9zpQUNfmCm7GtyuAC0Hy/t6o7xYjbNdj6UMz2WjWin7UZZlEQytq1vnobjb3AWhAq4FX9GyyJyArq1bngAH8+eDGzbu1KLSBzgdj1+YBFYcSlZmAysT11WHhXF0+5bqJwLUFDk9AKPbi3fcXzgPkle1GkgphnxwjR822Rb8eIRohlrLEZHz/zzSw6jJbLL7bVToYM+xVQeeKvAZLLcBIIgXkhHDMAIkjZGt21ZtOd1gDLFDKqG7vcZd4zNnozrg1RPxbOm1ntA4ImBTFqi99Hn7MbmEHdV2OtFJQrmUNA8jSnGJ7Ukopjqe9U6OZOnqLJLqeC8zWgiC+TdHrrt5aLBc2gX4kCSWZA4tt/TksLNVziiCSI/wccrZfg9Y+Tr8OFiVzLFSBwGELWxqtnUizP+lj7QE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
