travis:
  secure:
    BINSTAR_TOKEN: KqM6htQ09pl1GBT8rpDIdlETI/+fMjzn0eOygPikt9gV4gImrZ2t0uLOJcp6G+BQ1IX49zWkpg+uSw3QVRlT5qAen0KZvAFRBVP88seUMM97c1Zfld5RuXCu+b6vdGHzMeRSOJh5meE9IhkrYjMsEenmhwpxK9l3NPduWGa5ATBKB36ENNVf68unKC1rArL9XOHxf2SppDo71hbpuBpbyqqsExkan+ykFL0mMke+io6znIhl5uTZJLW+wYnowQrd2VLrIYd1v431TOd45i33KDHqXZM7AoVYNHZxgeYgZN7jAgHRmbWuT/Z72iNfeVVdzsIowPQCAgpnff/RsJDWNSKOzeQawD5i6lTWlrhNYka4IXoyFNmAPkr0n4ekoTXuWX61eIsPKr8KxDv4f2AhnJJrpN9ThvUFwUdwmaM5YfFiF6MsooXqMwZ9eb1HdwZLqSe53X9Oh+NHf37o0dHvAZC1Rjfkx0jVBP1D/G2z7lNKeP5SRdIIwwISANbU/q0o3CfEYt50CxhZoiEtKXIG97Eehe0etirg5EoBqBHzYJVsXQJ6EP8wH6nOU07lHz5oDIj8fRmJdXXVI1s4BhH17rm039t6KMXAW0SJnEHi7qg/xerlrivYLBopoLpG+zrtCOepinDcFqWQyvSMJhLmQJXKZfMfsCGj9G4bsyO7kRo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
